spring:
  data:
    mongodb:
      uri: mongodb+srv://mrunmayik1220:manu192012@aws-deployment.7ddappq.mongodb.net/?appName=aws-deployment
      database: dbspringboot
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /journal
